### ISSUE TITLE
Aggiungere Vittorio Feltri

### ISSUE THREAD

**Issue by gimmi** [parenzo/parenzo.github.io#1]
"Tu sei cafone nell'anima"
"Se non hai argomenti stai zitto pistolino"

...e altre perle

**Comment by parenzo** [comment]
Ne ho messe un paio ma mi farebbe comodo una mano per trovarle (link a YouTube/podcast possibilmente con indicazione temporale). Contribuiamo tutti ad un mondo miserabilmente migliore.
